Check dependencies

diff --git a/guest b/guest
--- a/guest
+++ b/guest
@@ -1,19 +1,32 @@
 #!/bin/sh
+pairinguser="pairing@mumble.ugent.be"
+
 set -e
+
+abduco   > /dev/null 2>&1 || { echo 'abduco found: no' && exit 1; }
+socat -h > /dev/null 2>&1 || { echo 'socat found: no' && exit 1; }
+ssh -V   > /dev/null 2>&1 || { echo 'ssh found: no' && exit 1; }
 
 if ! printf '%s' "$1" | grep '^[a-z0-9-]\+$'; then
 	echo 'Please provide an alphanumeric (and -) session name'
 	exit 1
 fi
 
-socket="$(mktemp)"
-rm "$socket"
+# Create a temporary directory for our sockets
+umask 077
+socketdir="$(mktemp -d)"
+trap "rm -rf '$socketdir'" EXIT
 
-socat exec:"ssh -M pairing@mumble.ugent.be 'guest $1'" unix-listen:"$socket",fork,reuseaddr,unlink-early &
+# Connect a remote socket to a local socket
+socat exec:"ssh -M '$pairinguser' 'guest $1'" unix-listen:"$socketdir/abduco",fork,reuseaddr,unlink-early &
 socatpid="$!"
+
+# Give socat some time to initialize
 sleep 1
 
-abduco -a "$socket"
+# Connect to the local socket
+abduco -a "$socketdir/abduco"
 
+# Cleanup
 kill "$socatpid"
 wait
